version: '3.1'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
